#!/usr/bin/env python3
"""
Emit the agent-facing catalogue and state-machine index for the
canonical MLS business processes.

Reads:
  raw/citations.csv (produced by 01_validate_citations.py)
  processes/*.md
  ../../data-models/reso-dd-kb/raw/{resources,fields,lookup_values}.csv

Writes:
  wiki/agent-docs/_index.md
  wiki/agent-docs/state_machines.md
  raw/coverage.csv

Phase: Emit (deterministic, no hand-edits to outputs).
Owner: scripts/02_emit_index.py - do NOT hand-edit any of the
files listed under "Writes".

Determinism contract:
  - Re-running this script with no input changes MUST produce
    zero-byte diffs in every output file.
  - All iteration is over sorted collections.
  - All timestamps are derived from input mtimes (or absent).
"""

from __future__ import annotations

import csv
import re
import sys
from collections import defaultdict
from pathlib import Path

KB_ROOT = Path(__file__).resolve().parent.parent
RESO_RAW = KB_ROOT.parent.parent / "data-models" / "reso-dd-kb" / "raw"
PROCESSES_DIR = KB_ROOT / "processes"
CITATIONS_CSV = KB_ROOT / "raw" / "citations.csv"
WIKI_DIR = KB_ROOT / "wiki" / "agent-docs"
INDEX_OUT = WIKI_DIR / "_index.md"
SM_OUT = WIKI_DIR / "state_machines.md"
COVERAGE_OUT = KB_ROOT / "raw" / "coverage.csv"

H1_RE = re.compile(r"^#\s+(?P<title>.+)$", re.MULTILINE)
SCOPE_RE = re.compile(
    r"^## Scope\s*\n+(?P<body>.*?)(?=^## )", re.DOTALL | re.MULTILINE
)
MERMAID_RE = re.compile(
    r"```mermaid\s*\n(?P<body>.*?)\n```",
    re.DOTALL,
)


def load_citations() -> list[dict]:
    with CITATIONS_CSV.open("r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def extract_title(text: str) -> str:
    m = H1_RE.search(text)
    if not m:
        return "(untitled)"
    return m.group("title").strip()


def extract_scope(text: str) -> str:
    m = SCOPE_RE.search(text + "\n## ")
    if not m:
        return ""
    body = m.group("body").strip()
    in_scope: list[str] = []
    keep = False
    for line in body.splitlines():
        stripped = line.strip()
        if stripped.lower().startswith("in scope"):
            keep = True
            continue
        if stripped.lower().startswith("out of scope"):
            break
        if keep and stripped.startswith("- "):
            in_scope.append(stripped[2:].rstrip("."))
    return "; ".join(in_scope[:3])


def extract_mermaid_blocks(text: str) -> list[str]:
    return [m.group("body").strip() for m in MERMAID_RE.finditer(text)]


def main() -> int:
    if not CITATIONS_CSV.is_file():
        print(
            f"ERROR: {CITATIONS_CSV} not found; run 01_validate_citations.py first.",
            file=sys.stderr,
        )
        return 2
    if not PROCESSES_DIR.is_dir():
        print(f"ERROR: {PROCESSES_DIR} not found.", file=sys.stderr)
        return 2

    citations = load_citations()
    process_files = sorted(PROCESSES_DIR.glob("*.md"))

    process_meta: dict[str, dict] = {}
    for path in process_files:
        text = path.read_text(encoding="utf-8")
        process_meta[path.name] = {
            "path": path,
            "title": extract_title(text),
            "scope": extract_scope(text),
            "mermaid_blocks": extract_mermaid_blocks(text),
            "byte_count": len(text.encode("utf-8")),
            "line_count": text.count("\n") + (0 if text.endswith("\n") else 1),
        }

    # Coverage rollups: by process and by resource.
    by_process: dict[str, dict[str, int]] = defaultdict(
        lambda: {"Resource": 0, "Field": 0, "LookupValue": 0}
    )
    by_resource: dict[str, set[str]] = defaultdict(set)
    by_lookup: dict[str, set[str]] = defaultdict(set)
    cited_resources: set[str] = set()
    cited_fields: set[tuple[str, str]] = set()
    cited_lookup_values: set[tuple[str, str]] = set()

    for c in citations:
        proc = c["process"]
        kind = c["citation_kind"]
        val = c["citation_value"]
        by_process[proc][kind] = by_process[proc].get(kind, 0) + 1
        if kind == "Resource":
            cited_resources.add(val)
            by_resource[val].add(proc)
        elif kind == "Field":
            res, fld = val.split(".", 1)
            cited_fields.add((res, fld))
            by_resource[res].add(proc)
        elif kind == "LookupValue":
            lk, lv = val.split(".", 1)
            cited_lookup_values.add((lk, lv))
            by_lookup[lk].add(proc)

    # _index.md
    INDEX_OUT.parent.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    lines.append("# Canonical MLS business processes - agent index\n")
    lines.append(
        "Generated by `scripts/02_emit_index.py`. Do NOT hand-edit. "
        "Re-run after editing `processes/*.md` and re-running "
        "`01_validate_citations.py`.\n"
    )
    lines.append("## Process catalogue\n")
    lines.append(
        "| Process | Title | Citations (R/F/LV) | Mermaid blocks | Bytes |"
    )
    lines.append("|---|---|---|---|---|")
    for name in sorted(process_meta):
        meta = process_meta[name]
        c = by_process.get(name, {"Resource": 0, "Field": 0, "LookupValue": 0})
        lines.append(
            f"| [`{name}`](../../processes/{name}) "
            f"| {meta['title']} "
            f"| {c.get('Resource', 0)} / {c.get('Field', 0)} / {c.get('LookupValue', 0)} "
            f"| {len(meta['mermaid_blocks'])} "
            f"| {meta['byte_count']} |"
        )

    lines.append("")
    lines.append("## RESO resource coverage\n")
    lines.append(
        "Resources cited by at least one process. The map "
        "answers \"which process documents this resource?\".\n"
    )
    lines.append("| Resource | Process(es) | Citations |")
    lines.append("|---|---|---|")
    for res in sorted(by_resource):
        procs = sorted(by_resource[res])
        cite_count = sum(
            1 for c in citations if (
                c["citation_kind"] == "Resource" and c["citation_value"] == res
            ) or (
                c["citation_kind"] == "Field"
                and c["citation_value"].split(".", 1)[0] == res
            )
        )
        proc_links = ", ".join(
            f"[`{p}`](../../processes/{p})" for p in procs
        )
        lines.append(f"| `{res}` | {proc_links} | {cite_count} |")

    lines.append("")
    lines.append("## RESO lookup coverage\n")
    lines.append(
        "Lookups cited by at least one process. Each row lists the "
        "lookup name and the processes that reference its values.\n"
    )
    lines.append("| Lookup | Process(es) | Distinct values cited |")
    lines.append("|---|---|---|")
    for lk in sorted(by_lookup):
        procs = sorted(by_lookup[lk])
        proc_links = ", ".join(
            f"[`{p}`](../../processes/{p})" for p in procs
        )
        n = sum(1 for L, _v in cited_lookup_values if L == lk)
        lines.append(f"| `{lk}` | {proc_links} | {n} |")

    lines.append("")
    lines.append("## Roll-up totals\n")
    lines.append(f"- Processes: **{len(process_meta)}**")
    lines.append(f"- Total citations: **{len(citations)}**")
    lines.append(
        f"- Distinct cited resources: **{len(cited_resources | {r for r,_ in cited_fields})}**"
    )
    lines.append(f"- Distinct cited fields: **{len(cited_fields)}**")
    lines.append(
        f"- Distinct cited lookup values: **{len(cited_lookup_values)}**"
    )
    lines.append(f"- Distinct cited lookups: **{len(by_lookup)}**")
    lines.append("")
    lines.append("See [`state_machines.md`](state_machines.md) for the per-process state diagrams.\n")

    INDEX_OUT.write_text("\n".join(lines), encoding="utf-8")

    # state_machines.md (concatenation of all primary mermaid blocks)
    sm_lines: list[str] = []
    sm_lines.append("# Canonical MLS state machines\n")
    sm_lines.append(
        "Generated by `scripts/02_emit_index.py`. Do NOT hand-edit. "
        "This file concatenates the mermaid `stateDiagram-v2` blocks "
        "from each process file for at-a-glance review.\n"
    )
    for name in sorted(process_meta):
        meta = process_meta[name]
        sm_lines.append(f"## {meta['title']}\n")
        sm_lines.append(f"Source: [`processes/{name}`](../../processes/{name})\n")
        if not meta["mermaid_blocks"]:
            sm_lines.append("_(no mermaid blocks)_\n")
            continue
        for i, block in enumerate(meta["mermaid_blocks"], 1):
            if len(meta["mermaid_blocks"]) > 1:
                sm_lines.append(f"### Diagram {i}\n")
            sm_lines.append("```mermaid")
            sm_lines.append(block)
            sm_lines.append("```\n")

    SM_OUT.write_text("\n".join(sm_lines), encoding="utf-8")

    # raw/coverage.csv (one row per process)
    COVERAGE_OUT.parent.mkdir(parents=True, exist_ok=True)
    coverage_rows: list[dict] = []
    for name in sorted(process_meta):
        meta = process_meta[name]
        c = by_process.get(name, {"Resource": 0, "Field": 0, "LookupValue": 0})
        coverage_rows.append(
            {
                "process": name,
                "title": meta["title"],
                "scope_summary": meta["scope"],
                "mermaid_blocks": len(meta["mermaid_blocks"]),
                "byte_count": meta["byte_count"],
                "line_count": meta["line_count"],
                "resource_citations": c.get("Resource", 0),
                "field_citations": c.get("Field", 0),
                "lookup_value_citations": c.get("LookupValue", 0),
                "total_citations": (
                    c.get("Resource", 0)
                    + c.get("Field", 0)
                    + c.get("LookupValue", 0)
                ),
            }
        )

    with COVERAGE_OUT.open("w", encoding="utf-8", newline="") as fh:
        writer = csv.DictWriter(
            fh,
            fieldnames=[
                "process",
                "title",
                "scope_summary",
                "mermaid_blocks",
                "byte_count",
                "line_count",
                "resource_citations",
                "field_citations",
                "lookup_value_citations",
                "total_citations",
            ],
            quoting=csv.QUOTE_MINIMAL,
        )
        writer.writeheader()
        writer.writerows(coverage_rows)

    print(
        f"[02] emit_index: emitted "
        f"wiki/agent-docs/_index.md ({INDEX_OUT.stat().st_size}B), "
        f"wiki/agent-docs/state_machines.md ({SM_OUT.stat().st_size}B), "
        f"raw/coverage.csv ({len(coverage_rows)} rows)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
