#!/usr/bin/env python3
"""
Generate the markdown bundle for source-mappings.

Reads:
  raw/alignment_<resource>.csv         (6 files)
  raw/dash_inventory.csv
  raw/qobrix_inventory.csv
  raw/cbp_inventory.csv
  raw/mapping_curated.csv
  ../reso-dd-kb/raw/fields.csv

Writes:
  wiki/agent-docs/_index.md
  wiki/agent-docs/by_resource/<resource>.md          (6 files)
  wiki/agent-docs/by_source/dash.md
  wiki/agent-docs/by_source/qobrix.md
  wiki/agent-docs/by_source/sir-business-practice.md
  wiki/agent-docs/extensions.md
  wiki/agent-docs/lookup_value_mappings.md

Phase: Emit (mechanical, deterministic).
Owner: scripts/05_emit_mapping_docs.py - do NOT hand-edit wiki/agent-docs/**.
"""

from __future__ import annotations

import csv
import json
import sys
from pathlib import Path

KB_ROOT = Path(__file__).resolve().parent.parent
RESO_RAW = KB_ROOT.parent / "reso-dd-kb" / "raw"
RAW = KB_ROOT / "raw"
OUT_DIR = KB_ROOT / "wiki" / "agent-docs"

IN_SCOPE_RESOURCES = ["Property", "Member", "Office", "Contacts", "Teams", "Media"]


def load_csv(path: Path) -> list[dict]:
    with path.open("r", encoding="utf-8", newline="") as fh:
        return list(csv.DictReader(fh))


def md_escape(text: str) -> str:
    """Escape pipe characters and trim whitespace for markdown tables."""
    if not text:
        return ""
    return (
        text.replace("\r\n", " ")
        .replace("\n", " ")
        .replace("|", "\\|")
        .strip()
    )


def reso_field_link(resource: str, field: str) -> str:
    """Cross-reference the canonical RESO docs (relative path)."""
    snake = "_".join(
        c if c.isupper() else c
        for c in field
    )
    # Use case-preserving form; reso-dd-kb stores resources by lowercase + per_field.
    return f"../../../reso-dd-kb/wiki/agent-docs/resources/{resource.lower()}.md#{field.lower()}"


def render_table(headers: list[str], rows: list[list[str]]) -> str:
    out = ["| " + " | ".join(headers) + " |"]
    out.append("|" + "|".join(["---"] * len(headers)) + "|")
    for r in rows:
        out.append("| " + " | ".join(md_escape(c) for c in r) + " |")
    return "\n".join(out)


def emit_by_resource(resource: str, alignment_rows: list[dict], out_path: Path) -> dict:
    natives = [r for r in alignment_rows if r["is_extension"] == "false"]
    extensions = [r for r in alignment_rows if r["is_extension"] == "true"]

    has_dash = sum(1 for r in alignment_rows if r["has_dash"] == "yes")
    has_qobrix = sum(1 for r in alignment_rows if r["has_qobrix"] == "yes")
    has_sir = sum(1 for r in alignment_rows if r["has_sir"] == "yes")

    # Coverage gaps: native fields where no source carries it (rare; this
    # surfaces curator errors more often than real RESO-only fields).
    coverage_gaps = [
        r["reso_field"]
        for r in natives
        if r["has_dash"] == "no" and r["has_qobrix"] == "no" and r["has_sir"] == "no"
    ]

    lines: list[str] = []
    lines.append(f"# {resource} - source-to-RESO mapping")
    lines.append("")
    lines.append("> Generated by `scripts/05_emit_mapping_docs.py`. Do NOT hand-edit.")
    lines.append("> Source of truth: [`raw/mapping_curated.csv`](../../../raw/mapping_curated.csv).")
    lines.append(
        f"> Canonical RESO definitions: [`reso-dd-kb/wiki/agent-docs/resources/{resource.lower()}.md`]"
        f"(../../../../reso-dd-kb/wiki/agent-docs/resources/{resource.lower()}.md)."
    )
    lines.append("")
    lines.append(
        f"**{resource}**: {len(alignment_rows)} rows curated "
        f"({len(natives)} canonical RESO fields, {len(extensions)} `x_sm_*` extensions). "
        f"Coverage flags (any-of-three): Dash {has_dash}, Qobrix {has_qobrix}, SIR {has_sir}."
    )
    lines.append("")

    lines.append("## Canonical RESO fields")
    lines.append("")
    if natives:
        rows = []
        for r in natives:
            dash_display = ""
            if r["dash_label"]:
                form = r["dash_form"] or ""
                dash_display = f"{form} / {r['dash_label']}" if form else r["dash_label"]
            qobrix_display = ""
            if r["qobrix_path"]:
                qobrix_display = f"{r['qobrix_schema']}/{r['qobrix_path']}" if r["qobrix_schema"] else r["qobrix_path"]
            rows.append(
                [
                    r["reso_field"],
                    r["reso_data_type"],
                    r["reso_lookup"],
                    dash_display,
                    qobrix_display,
                    r["sir_label"],
                    r["confidence"],
                    r["notes"],
                ]
            )
        lines.append(
            render_table(
                ["RESO field", "Type", "Lookup", "Dash (form / label)", "Qobrix (schema/path)", "SIR label", "Conf.", "Notes"],
                rows,
            )
        )
    else:
        lines.append("_No canonical RESO mappings curated yet for this resource._")
    lines.append("")

    lines.append("## Extensions (`x_sm_*`)")
    lines.append("")
    if extensions:
        rows = []
        for r in extensions:
            dash_display = ""
            if r["dash_label"]:
                form = r["dash_form"] or ""
                dash_display = f"{form} / {r['dash_label']}" if form else r["dash_label"]
            qobrix_display = ""
            if r["qobrix_path"]:
                qobrix_display = f"{r['qobrix_schema']}/{r['qobrix_path']}" if r["qobrix_schema"] else r["qobrix_path"]
            rows.append(
                [
                    r["reso_field"],
                    dash_display,
                    qobrix_display,
                    r["sir_label"],
                    r["confidence"],
                    r["notes"],
                ]
            )
        lines.append(
            render_table(
                ["Extension field", "Dash", "Qobrix", "SIR", "Conf.", "Notes"],
                rows,
            )
        )
        lines.append("")
        lines.append(
            "> Each `x_sm_*` row above MUST be governed in "
            "[`platform-extensions.md`](../../../../platform-extensions.md). "
            "Extensions surfaced here are gap signals, not formal adoptions."
        )
    else:
        lines.append("_No extensions curated for this resource._")
    lines.append("")

    lines.append("## Lookup value mappings")
    lines.append("")
    lookup_sections: list[str] = []
    for r in alignment_rows:
        if not r["value_mapping_json"]:
            continue
        try:
            vmap = json.loads(r["value_mapping_json"])
        except json.JSONDecodeError:
            continue
        section: list[str] = []
        section.append(f"### {r['reso_field']}")
        if r["reso_lookup"]:
            section.append(f"- RESO lookup: `{r['reso_lookup']}`")
        section.append("")
        section.append("| Source value | RESO standard value |")
        section.append("|---|---|")
        for src, tgt in sorted(vmap.items()):
            section.append(f"| `{md_escape(str(src))}` | `{md_escape(str(tgt))}` |")
        section.append("")
        lookup_sections.append("\n".join(section))
    if lookup_sections:
        lines.extend(lookup_sections)
    else:
        lines.append("_No source-side lookup value translations curated for this resource._")
    lines.append("")

    if coverage_gaps:
        lines.append("## Coverage gaps (no source carries the field)")
        lines.append("")
        for f in coverage_gaps:
            lines.append(f"- `{f}`")
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return {
        "resource": resource,
        "total": len(alignment_rows),
        "extensions": len(extensions),
        "has_dash": has_dash,
        "has_qobrix": has_qobrix,
        "has_sir": has_sir,
    }


def emit_by_source_dash(curated: list[dict], dash_inv: list[dict], out_path: Path) -> None:
    # Dash labels mapped via curated.
    mapped: dict[str, list[dict]] = {}
    for c in curated:
        if c["dash_label"]:
            mapped.setdefault(c["dash_label"], []).append(c)

    # Group by form, then section.
    forms: dict[str, dict[str, list[dict]]] = {}
    for r in dash_inv:
        if r["kind"] != "field":
            continue
        forms.setdefault(r["form"], {}).setdefault(r["section"], []).append(r)

    lines: list[str] = []
    lines.append("# Dash forms - field-by-field mapping to RESO")
    lines.append("")
    lines.append("> Generated by `scripts/05_emit_mapping_docs.py`. Do NOT hand-edit.")
    lines.append("> Source: 6 `BlankForm_*.docx` listing-form templates (`raw/dash/`).")
    lines.append("")
    lines.append("| Form | Section | Dash label | RESO target | Extension? | Notes |")
    lines.append("|---|---|---|---|---|---|")

    rows_count = 0
    for form, sections in sorted(forms.items()):
        for section, fields in sorted(sections.items()):
            for f in sorted(fields, key=lambda r: r["field_label"]):
                m = mapped.get(f["field_label"])
                if m:
                    # Pick the row whose dash_form matches if present, else the first.
                    pick = next((r for r in m if r["dash_form"] == form), m[0])
                    target = f"`{pick['reso_resource']}.{pick['reso_field']}`"
                    is_ext = "yes" if pick["is_extension"] == "true" else ""
                    notes = pick["notes"]
                else:
                    target = "_(unmapped)_"
                    is_ext = ""
                    notes = ""
                lines.append(
                    f"| {md_escape(form)} | {md_escape(section)} | {md_escape(f['field_label'])} | {md_escape(target)} | {is_ext} | {md_escape(notes)} |"
                )
                rows_count += 1

    lines.append("")
    lines.append(f"_Total Dash field rows: {rows_count}._")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_by_source_qobrix(curated: list[dict], qobrix_inv: list[dict], out_path: Path) -> None:
    mapped: dict[tuple[str, str], dict] = {}
    for c in curated:
        if c["qobrix_path"]:
            mapped[(c["qobrix_schema"], c["qobrix_path"])] = c

    schemas: dict[str, list[dict]] = {}
    for r in qobrix_inv:
        schemas.setdefault(r["schema"], []).append(r)

    lines: list[str] = []
    lines.append("# Qobrix - field-by-field mapping to RESO")
    lines.append("")
    lines.append("> Generated by `scripts/05_emit_mapping_docs.py`. Do NOT hand-edit.")
    lines.append("> Source: `raw/qobrix/qobrix_openapi.yaml` (in-scope schemas: Property, PropertyCoordinates, Contact, Agent, User, Group, Media, MediaResponse, MediaFile, MediaRequest).")
    lines.append("")

    for schema, props in sorted(schemas.items()):
        lines.append(f"## {schema}")
        lines.append("")
        lines.append("| Path | Type | RESO target | Extension? | Notes |")
        lines.append("|---|---|---|---|---|")
        for p in sorted(props, key=lambda r: r["property_path"]):
            m = mapped.get((schema, p["property_path"]))
            if m:
                target = f"`{m['reso_resource']}.{m['reso_field']}`"
                is_ext = "yes" if m["is_extension"] == "true" else ""
                notes = m["notes"]
            else:
                target = "_(unmapped)_"
                is_ext = ""
                notes = ""
            type_display = p["type"]
            if p["items_type"]:
                type_display += f"<{p['items_type']}>"
            lines.append(
                f"| `{md_escape(p['property_path'])}` | {md_escape(type_display)} | {md_escape(target)} | {is_ext} | {md_escape(notes)} |"
            )
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_by_source_sir(curated: list[dict], cbp_inv: list[dict], out_path: Path) -> None:
    mapped: dict[str, list[dict]] = {}
    for c in curated:
        if c["sir_label"]:
            mapped.setdefault(c["sir_label"], []).append(c)

    sheets: dict[tuple[str, str], dict[str, list[dict]]] = {}
    for r in cbp_inv:
        if r["kind"] not in ("field", "step"):
            continue
        sheets.setdefault((r["checklist"], r["sheet"]), {}).setdefault(r["section"], []).append(r)

    lines: list[str] = []
    lines.append("# SIR business practice - checklist-to-RESO mapping")
    lines.append("")
    lines.append("> Generated by `scripts/05_emit_mapping_docs.py`. Do NOT hand-edit.")
    lines.append("> Source: `raw/current-business-practice/*.xlsx` listing checklists.")
    lines.append("")

    rows_count = 0
    for (checklist, sheet), sections in sorted(sheets.items()):
        lines.append(f"## {checklist} / {sheet}")
        lines.append("")
        lines.append("| Section | Step / field label | Kind | RESO target | Extension? |")
        lines.append("|---|---|---|---|---|")
        for section, items in sorted(sections.items()):
            seen_in_section = set()
            for it in sorted(items, key=lambda r: r["step_label"]):
                if it["step_label"] in seen_in_section:
                    continue
                seen_in_section.add(it["step_label"])
                m = mapped.get(it["step_label"])
                if m:
                    pick = m[0]
                    target = f"`{pick['reso_resource']}.{pick['reso_field']}`"
                    is_ext = "yes" if pick["is_extension"] == "true" else ""
                else:
                    target = "_(unmapped)_"
                    is_ext = ""
                lines.append(
                    f"| {md_escape(section)} | {md_escape(it['step_label'])} | {md_escape(it['kind'])} | {md_escape(target)} | {is_ext} |"
                )
                rows_count += 1
        lines.append("")

    lines.append(f"_Total SIR checklist rows shown: {rows_count}._")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def emit_extensions(curated: list[dict], out_path: Path) -> int:
    extensions = [c for c in curated if c["is_extension"] == "true"]
    by_res: dict[str, list[dict]] = {}
    for c in extensions:
        by_res.setdefault(c["reso_resource"], []).append(c)

    lines: list[str] = []
    lines.append("# `x_sm_*` extensions surfaced by source mapping")
    lines.append("")
    lines.append("> Generated by `scripts/05_emit_mapping_docs.py`. Do NOT hand-edit.")
    lines.append(
        "> Each row below is a candidate or current Sharp Matrix extension. "
        "Every entry MUST be governed in "
        "[`platform-extensions.md`](../../../platform-extensions.md) - "
        "extensions surfaced here without a governance entry are gaps to fix."
    )
    lines.append("")
    lines.append(f"**Total**: {len(extensions)} extensions across {len(by_res)} resources.")
    lines.append("")
    for res, rows in sorted(by_res.items()):
        lines.append(f"## {res}")
        lines.append("")
        lines.append("| Extension field | Dash | Qobrix | SIR | Notes |")
        lines.append("|---|---|---|---|---|")
        for r in sorted(rows, key=lambda x: x["reso_field"]):
            dash_disp = ""
            if r["dash_label"]:
                form = r["dash_form"] or ""
                dash_disp = f"{form} / {r['dash_label']}" if form else r["dash_label"]
            qobrix_disp = ""
            if r["qobrix_path"]:
                qobrix_disp = f"{r['qobrix_schema']}/{r['qobrix_path']}" if r["qobrix_schema"] else r["qobrix_path"]
            lines.append(
                f"| `{md_escape(r['reso_field'])}` | {md_escape(dash_disp)} | {md_escape(qobrix_disp)} | {md_escape(r['sir_label'])} | {md_escape(r['notes'])} |"
            )
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(extensions)


def emit_lookup_value_mappings(curated: list[dict], out_path: Path) -> int:
    rows = [c for c in curated if c["value_mapping_json"]]

    lines: list[str] = []
    lines.append("# Lookup value mappings (source-side -> RESO StandardValue)")
    lines.append("")
    lines.append("> Generated by `scripts/05_emit_mapping_docs.py`. Do NOT hand-edit.")
    lines.append(
        "> The 5th hard-fail join gate ensures every target value below is a real "
        "`StandardValue` in `reso-dd-kb/raw/lookup_values.csv`."
    )
    lines.append("")

    by_res: dict[str, list[dict]] = {}
    for r in rows:
        by_res.setdefault(r["reso_resource"], []).append(r)

    for res, items in sorted(by_res.items()):
        lines.append(f"## {res}")
        lines.append("")
        for r in sorted(items, key=lambda x: x["reso_field"]):
            lines.append(f"### `{r['reso_field']}`")
            try:
                vmap = json.loads(r["value_mapping_json"])
            except json.JSONDecodeError:
                continue
            sources = []
            if r["dash_label"]:
                sources.append(f"Dash `{r['dash_label']}`")
            if r["qobrix_path"]:
                sources.append(f"Qobrix `{r['qobrix_schema']}/{r['qobrix_path']}`")
            if r["sir_label"]:
                sources.append(f"SIR `{r['sir_label']}`")
            lines.append("- Source(s): " + (", ".join(sources) if sources else "_(none)_"))
            lines.append("")
            lines.append("| Source value | RESO StandardValue |")
            lines.append("|---|---|")
            for src, tgt in sorted(vmap.items()):
                lines.append(f"| `{md_escape(str(src))}` | `{md_escape(str(tgt))}` |")
            lines.append("")
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return len(rows)


def emit_index(stats: list[dict], extension_count: int, lookup_count: int, out_path: Path) -> None:
    lines: list[str] = []
    lines.append("# Source mappings - index")
    lines.append("")
    lines.append("> Generated by `scripts/05_emit_mapping_docs.py`. Do NOT hand-edit.")
    lines.append("> Regenerate with: `python scripts/01..03_inventory_*.py && python scripts/04_join_alignment.py && python scripts/05_emit_mapping_docs.py`.")
    lines.append("")
    lines.append("## Per-resource pages")
    lines.append("")
    lines.append("| Resource | Total rows | Extensions | Has Dash | Has Qobrix | Has SIR | Page |")
    lines.append("|---|---|---|---|---|---|---|")
    for s in stats:
        lines.append(
            f"| {s['resource']} | {s['total']} | {s['extensions']} | "
            f"{s['has_dash']} | {s['has_qobrix']} | {s['has_sir']} | "
            f"[`by_resource/{s['resource'].lower()}.md`](by_resource/{s['resource'].lower()}.md) |"
        )
    lines.append("")
    lines.append("## Per-source pages")
    lines.append("")
    lines.append("- [`by_source/dash.md`](by_source/dash.md) - Dash form fields")
    lines.append("- [`by_source/qobrix.md`](by_source/qobrix.md) - Qobrix OpenAPI schemas")
    lines.append("- [`by_source/sir-business-practice.md`](by_source/sir-business-practice.md) - SIR XLSX checklists")
    lines.append("")
    lines.append("## Cross-cutting pages")
    lines.append("")
    lines.append(f"- [`extensions.md`](extensions.md) - {extension_count} `x_sm_*` extension candidates / adoptions")
    lines.append(f"- [`lookup_value_mappings.md`](lookup_value_mappings.md) - {lookup_count} curated source -> RESO value translations")
    lines.append("")
    lines.append("## Pipeline status")
    lines.append("")
    lines.append("- 5/5 hard-fail join gates passed (otherwise `04_join_alignment.py` exits non-zero).")
    lines.append("- Inventories deterministic (sorted, stable column order, no timestamps).")
    lines.append("- Curated CSV is the only hand-edited input; alignments + this markdown are regenerated.")
    lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> int:
    curated = load_csv(RAW / "mapping_curated.csv")
    dash_inv = load_csv(RAW / "dash_inventory.csv")
    qobrix_inv = load_csv(RAW / "qobrix_inventory.csv")
    cbp_inv = load_csv(RAW / "cbp_inventory.csv")

    stats: list[dict] = []
    for resource in IN_SCOPE_RESOURCES:
        align_path = RAW / f"alignment_{resource.lower()}.csv"
        if not align_path.is_file():
            print(f"ERROR: missing {align_path}; run scripts/04_join_alignment.py first", file=sys.stderr)
            return 2
        alignment_rows = load_csv(align_path)
        out_path = OUT_DIR / "by_resource" / f"{resource.lower()}.md"
        s = emit_by_resource(resource, alignment_rows, out_path)
        stats.append(s)

    emit_by_source_dash(curated, dash_inv, OUT_DIR / "by_source" / "dash.md")
    emit_by_source_qobrix(curated, qobrix_inv, OUT_DIR / "by_source" / "qobrix.md")
    emit_by_source_sir(curated, cbp_inv, OUT_DIR / "by_source" / "sir-business-practice.md")
    extension_count = emit_extensions(curated, OUT_DIR / "extensions.md")
    lookup_count = emit_lookup_value_mappings(curated, OUT_DIR / "lookup_value_mappings.md")
    emit_index(stats, extension_count, lookup_count, OUT_DIR / "_index.md")

    print(f"[05] emit_mapping_docs: wrote markdown bundle under {OUT_DIR.relative_to(KB_ROOT)}/")
    print(f"     by_resource/: {len(stats)} files")
    print(f"     by_source/: 3 files (dash, qobrix, sir-business-practice)")
    print(f"     extensions.md: {extension_count} extensions")
    print(f"     lookup_value_mappings.md: {lookup_count} value-mapped fields")
    print(f"     _index.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
